apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.fullname" . }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "portfolio.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") (gt (int .Values.service.nodePort) 0) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
